# Generated by Django 2.0.1 on 2018-01-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=256)),
                ('alternativa_correcta', models.CharField(max_length=256)),
                ('alternativa_incorrecta_1', models.CharField(max_length=256)),
                ('alternativa_incorrecta_2', models.CharField(max_length=256)),
                ('alternativa_incorrecta_3', models.CharField(max_length=256)),
                ('tema', models.CharField(choices=[('T1', 'Tema1'), ('T2', 'Tema2'), ('T3', 'Tema3'), ('T4', 'Tema4')], max_length=4)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
            ],
        ),
    ]
