# Generated by Django 2.0.1 on 2018-01-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='categoria_AI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='categoria_AIIA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='categoria_AIIB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='categoria_AIIIA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='categoria_AIIIB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='categoria_AIIIC',
            field=models.BooleanField(default=False),
        ),
    ]
