# Generated by Django 2.0.1 on 2018-04-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180125_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='enunciado',
            field=models.CharField(max_length=556),
        ),
    ]
