# Generated by Django 2.0.1 on 2018-04-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20180405_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='alternativa_1',
            field=models.CharField(blank=True, max_length=456, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='alternativa_2',
            field=models.CharField(blank=True, max_length=456, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='alternativa_3',
            field=models.CharField(blank=True, max_length=456, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='alternativa_4',
            field=models.CharField(blank=True, max_length=456, null=True),
        ),
    ]
